version: 1

defaults:
  interval_seconds: 30
  timeout_ms: 2000
  retries: 2
  http:
    user_agent: "ThingConnectPulse/1.0-Testing"
    expect_text: "OK"

groups:
  - id: "network-devices"
    name: "Network Devices"
    color: "#00ff00"
    sort_order: 1
  
  - id: "web-services"
    name: "Web Services"  
    parent_id: "network-devices"
    color: "#0066cc"
    sort_order: 2

  - id: "databases"
    name: "Database Servers"
    color: "#ff6600"
    sort_order: 3

targets:
  - name: "Primary Router"
    host: "192.168.1.1"
    group: "network-devices"
    type: "icmp"
    interval_seconds: 10

  - name: "Google DNS"
    host: "8.8.8.8"
    group: "network-devices"
    type: "icmp"
    
  - name: "Company Website"
    host: "httpbin.org"
    port: 80
    path: "/status/200"
    group: "web-services"
    type: "http"
    expect_text: ""

  - name: "HTTPS Test Service"
    host: "httpbin.org"
    port: 443
    path: "/json"
    group: "web-services"
    type: "https"
    timeout_ms: 5000
    
  - name: "Database Server TCP"
    host: "127.0.0.1"
    port: 3306
    group: "databases"
    type: "tcp"
    interval_seconds: 60