# ThingConnect.Pulse - Simple Initial Configuration
# This configuration monitors essential public endpoints for testing
# Perfect for initial setup and validation

# Schema version - must be 1
version: 1

# Global defaults for all monitoring targets
defaults:
  # Check every 30 seconds
  interval_seconds: 30
  
  # 3 second timeout for internet endpoints
  timeout_ms: 3000
  
  # 1 retry attempt
  retries: 1
  
  # HTTP-specific settings
  http:
    user_agent: "ThingConnectPulse/1.0"
    expect_text: ""

# Logical groups for organizing endpoints
groups:
  # Essential internet services
  - id: internet-services
    name: "Internet Services"
    color: "#4285F4"    # Blue
    sort_order: 10
    
  # DNS providers
  - id: dns-providers
    name: "DNS Providers" 
    color: "#34C759"    # Green
    sort_order: 20
    
  # Development tools
  - id: dev-tools
    name: "Developer Tools"
    color: "#007AFF"    # Blue
    sort_order: 30

# Essential monitoring targets
targets:

  # ========================================
  # DNS Services (ICMP Ping Tests)
  # ========================================
  
  # Google Public DNS
  - type: icmp
    host: 8.8.8.8
    group: dns-providers
    name: "Google DNS"
    expected_rtt_ms: 25
    notes: "Google's public DNS server"
    
  # Cloudflare DNS
  - type: icmp
    host: 1.1.1.1
    group: dns-providers
    name: "Cloudflare DNS"
    expected_rtt_ms: 20
    notes: "Cloudflare's fast public DNS"

  # ========================================
  # Web Services (HTTP Tests)
  # ========================================
  
  # Google Search
  - type: http
    host: www.google.com
    port: 443
    http_path: "/"
    http_match: "Google"
    group: internet-services
    name: "Google"
    notes: "Google search engine"
    
  # GitHub
  - type: http
    host: github.com
    port: 443
    http_path: "/"
    http_match: "GitHub"
    group: dev-tools
    name: "GitHub"
    notes: "GitHub platform"
    
  # Cloudflare
  - type: http
    host: www.cloudflare.com
    port: 443
    http_path: "/"
    http_match: "Cloudflare"
    group: internet-services
    name: "Cloudflare"
    notes: "Cloudflare website"

  # ========================================
  # HTTP Testing Service
  # ========================================
  
  # Microsoft for testing
  - type: http
    host: www.microsoft.com
    port: 443
    http_path: "/"
    http_match: "Microsoft"
    group: internet-services
    name: "Microsoft"
    notes: "Microsoft corporate website"
    
  # ========================================
  # High-Frequency Example
  # ========================================
  
  # Frequent monitoring example
  - type: icmp
    host: 8.8.8.8
    group: dns-providers
    name: "Google DNS (Frequent)"
    interval_seconds: 15
    expected_rtt_ms: 25
    notes: "High-frequency monitoring example"